"""empty message

Revision ID: 518d12d18aa7
Revises: ee71f84143a2
Create Date: 2022-03-01 21:53:24.472483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518d12d18aa7'
down_revision = 'ee71f84143a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('botconfigs', sa.Column('subscribed', sa.Boolean(), nullable=True))
    op.add_column('botconfigs', sa.Column('subscription_start_date', sa.DateTime(), nullable=True))
    op.add_column('botconfigs', sa.Column('subscription_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('botconfigs', 'subscription_end_date')
    op.drop_column('botconfigs', 'subscription_start_date')
    op.drop_column('botconfigs', 'subscribed')
    # ### end Alembic commands ###
