"""empty message

Revision ID: c909e0b843fe
Revises: a36625945368
Create Date: 2022-03-08 10:22:52.134000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c909e0b843fe'
down_revision = 'a36625945368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('botconfigs', sa.Column('connected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('botconfigs', 'connected')
    # ### end Alembic commands ###
