"""empty message

Revision ID: e0eba30e8a6e
Revises: 518d12d18aa7
Create Date: 2022-03-02 09:09:10.895596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0eba30e8a6e'
down_revision = '518d12d18aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('botconfigs', sa.Column('subscription_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('botconfigs', 'subscription_type')
    # ### end Alembic commands ###
