"""empty message

Revision ID: ee71f84143a2
Revises: 
Create Date: 2022-02-28 16:13:31.158964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee71f84143a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botconfigs',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('secret')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('botconfigs')
    # ### end Alembic commands ###
