"""empty message

Revision ID: f23e5155335b
Revises: c909e0b843fe
Create Date: 2022-03-08 11:13:37.240908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23e5155335b'
down_revision = 'c909e0b843fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('botconfigs', sa.Column('subscription_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('botconfigs', 'subscription_status')
    # ### end Alembic commands ###
